const cloudSkills = [
  {
    id: 1,
    name: "Amazon Web Services (AWS)",
    category: "Cloud",
    designation: [
      { id: 101, title: "AWS Solutions Architect" },
      { id: 102, title: "AWS Cloud Engineer" },
      { id: 103, title: "AWS DevOps Engineer" },
      { id: 104, title: "AWS Security Specialist" },
      { id: 105, title: "AWS Certified Developer" },
      { id: 106, title: "AWS Big Data Specialist" },
    ],
  },
  {
    id: 2,
    name: "Microsoft Azure",
    category: "Cloud",
    designation: [
      { id: 201, title: "Azure Solutions Architect" },
      { id: 202, title: "Azure Cloud Developer" },
      { id: 203, title: "Azure DevOps Engineer" },
      { id: 204, title: "Azure AI Engineer" },
      { id: 205, title: "Azure Security Engineer" },
      { id: 206, title: "Azure Data Scientist" },
    ],
  },
  {
    id: 3,
    name: "Google Cloud Platform (GCP)",
    category: "Cloud",
    designation: [
      { id: 301, title: "GCP Cloud Architect" },
      { id: 302, title: "GCP Data Engineer" },
      { id: 303, title: "GCP DevOps Engineer" },
      { id: 304, title: "GCP Machine Learning Engineer" },
      { id: 305, title: "GCP Security Specialist" },
      { id: 306, title: "GCP Network Engineer" },
    ],
  },
  {
    id: 4,
    name: "Cloud Security",
    category: "Security",
    designation: [
      { id: 401, title: "Cloud Security Architect" },
      { id: 402, title: "Cloud Security Engineer" },
      { id: 403, title: "Cloud Compliance Analyst" },
      { id: 404, title: "Cloud Penetration Tester" },
      { id: 405, title: "Cloud Security Specialist" },
    ],
  },
  {
    id: 7,
    name: "IBM Cloud",
    category: "Cloud",
    designation: [
      { id: 701, title: "IBM Cloud Architect" },
      { id: 702, title: "IBM Cloud Developer" },
      { id: 703, title: "IBM Cloud Security Specialist" },
      { id: 704, title: "IBM Cloud Automation Engineer" },
      { id: 705, title: "IBM Cloud Network Specialist" },
      { id: 706, title: "IBM Cloud DevOps Engineer" },
    ],
  },
  {
    id: 8,
    name: "Cloud Data Management",
    category: "Data Management",
    designation: [
      { id: 801, title: "Cloud Data Architect" },
      { id: 802, title: "Cloud Data Engineer" },
      { id: 803, title: "Cloud Database Administrator" },
      { id: 804, title: "Cloud Data Integration Specialist" },
      { id: 805, title: "Cloud Data Governance Analyst" },
    ],
  },
  {
    id: 9,
    name: "Multi-Cloud Strategy",
    category: "Cloud",
    designation: [
      { id: 901, title: "Multi-Cloud Architect" },
      { id: 902, title: "Cloud Integration Specialist" },
      { id: 903, title: "Cloud Migration Consultant" },
      { id: 904, title: "Multi-Cloud Security Specialist" },
      { id: 905, title: "Cloud Optimization Analyst" },
    ],
  },
  {
    id: 10,
    name: "Cloud Native Development",
    category: "Development",
    designation: [
      { id: 1001, title: "Cloud Native Developer" },
      { id: 1002, title: "Cloud Application Architect" },
      { id: 1003, title: "Microservices Developer" },
      { id: 1004, title: "Serverless Computing Specialist" },
      { id: 1005, title: "Cloud API Engineer" },
    ],
  },
];
