const legacySkills = [
    {
      id: 1,
      name: "COBOL Programming",
      category: "Legacy",
      designation: [
        { id: 101, title: "COBOL Developer" },
        { id: 102, title: "Mainframe Programmer" },
        { id: 103, title: "Legacy System Analyst" },
        { id: 104, title: "COBOL System Architect" },
        { id: 105, title: "Mainframe Operations Specialist" },
        { id: 106, title: "Legacy Software Engineer" },
      ],
    },
    {
      id: 2,
      name: "AS/400 (IBM iSeries)",
      category: "Legacy",
      designation: [
        { id: 201, title: "AS/400 Developer" },
        { id: 202, title: "IBM iSeries Administrator" },
        { id: 203, title: "Legacy Application Support" },
        { id: 204, title: "AS/400 System Analyst" },
        { id: 205, title: "Legacy System Integrator" },
        { id: 206, title: "IBM iSeries Consultant" },
      ],
    },
    {
      id: 3,
      name: "Legacy Database Systems",
      category: "Legacy",
      designation: [
        { id: 301, title: "Database Administrator (Legacy)" },
        { id: 302, title: "Legacy DBA Specialist" },
        { id: 303, title: "Legacy Data Architect" },
        { id: 304, title: "Data Migration Specialist" },
        { id: 305, title: "Legacy Database Developer" },
        { id: 306, title: "Data Conversion Analyst" },
      ],
    },
    {
      id: 4,
      name: "Mainframe Technologies",
      category: "Legacy",
      designation: [
        { id: 401, title: "Mainframe System Engineer" },
        { id: 402, title: "Legacy Systems Manager" },
        { id: 403, title: "Mainframe Security Specialist" },
        { id: 404, title: "Legacy Technology Consultant" },
        { id: 405, title: "Mainframe Performance Analyst" },
        { id: 406, title: "Legacy Systems Auditor" },
      ],
    },
    {
      id: 5,
      name: "Legacy Application Modernization",
      category: "Legacy",
      designation: [
        { id: 501, title: "Legacy Modernization Architect" },
        { id: 502, title: "Application Reengineering Specialist" },
        { id: 503, title: "Legacy Code Refactoring Engineer" },
        { id: 504, title: "Migration Project Manager" },
        { id: 505, title: "Legacy UX/UI Designer" },
        { id: 506, title: "Legacy Integration Specialist" },
      ],
    },
    {
      id: 6,
      name: "Legacy System Maintenance",
      category: "Legacy",
      designation: [
        { id: 601, title: "Legacy System Maintenance Engineer" },
        { id: 602, title: "Legacy Patch Management Specialist" },
        { id: 603, title: "Legacy System Support Analyst" },
        { id: 604, title: "Legacy Version Control Manager" },
        { id: 605, title: "Legacy Release Coordinator" },
        { id: 606, title: "Legacy Documentation Specialist" },
      ],
    },
    {
      id: 7,
      name: "Legacy Network Administration",
      category: "Legacy",
      designation: [
        { id: 701, title: "Legacy Network Administrator" },
        { id: 702, title: "Legacy Network Security Specialist" },
        { id: 703, title: "Legacy Network Architect" },
        { id: 704, title: "Legacy Network Support Engineer" },
        { id: 705, title: "Legacy Network Operations Manager" },
        { id: 706, title: "Legacy Network Performance Analyst" },
      ],
    },
    {
      id: 8,
      name: "Legacy QA and Testing",
      category: "Legacy",
      designation: [
        { id: 801, title: "Legacy QA Tester" },
        { id: 802, title: "Legacy Test Automation Engineer" },
        { id: 803, title: "Legacy Quality Assurance Manager" },
        { id: 804, title: "Legacy Performance Testing Specialist" },
        { id: 805, title: "Legacy Test Data Analyst" },
        { id: 806, title: "Legacy Usability Tester" },
      ],
    },
    {
      id: 9,
      name: "Legacy Business Analyst",
      category: "Legacy",
      designation: [
        { id: 901, title: "Legacy Business Analyst" },
        { id: 902, title: "Legacy Process Analyst" },
        { id: 903, title: "Legacy Requirements Analyst" },
        { id: 904, title: "Legacy Business Systems Analyst" },
        { id: 905, title: "Legacy Business Intelligence Analyst" },
        { id: 906, title: "Legacy Data Analyst" },
      ],
    },
    {
      id: 10,
      name: "Legacy Technical Writer",
      category: "Legacy",
      designation: [
        { id: 1001, title: "Legacy Technical Writer" },
        { id: 1002, title: "Documentation Specialist" },
        { id: 1003, title: "Legacy Content Editor" },
        { id: 1004, title: "Legacy Knowledge Management Specialist" },
        { id: 1005, title: "Legacy Instructional Designer" },
        { id: 1006, title: "Legacy Documentation Manager" },
      ],
    },
  ];
  
  
  