const sapSkills = [
  {
    id: 1,
    name: "SAP ERP",
    category: "ERP",
    designation: [
      { id: 101, title: "SAP Functional Consultant" },
      { id: 102, title: "SAP Technical Consultant" },
      { id: 103, title: "SAP ABAP Developer" },
      { id: 104, title: "SAP Basis Administrator" },
      { id: 105, title: "SAP Project Manager" },
      { id: 106, title: "SAP FICO Consultant" },
    ],
  },
  {
    id: 2,
    name: "SAP S/4HANA",
    category: "ERP",
    designation: [
      { id: 201, title: "SAP S/4HANA Consultant" },
      { id: 202, title: "SAP Fiori Developer" },
      { id: 203, title: "SAP S/4HANA Finance Consultant" },
      { id: 204, title: "SAP S/4HANA Logistics Consultant" },
      { id: 205, title: "SAP S/4HANA Technical Architect" },
      { id: 206, title: "SAP S/4HANA Integration Specialist" },
    ],
  },
  {
    id: 3,
    name: "SAP BW/BI",
    category: "Business Intelligence",
    designation: [
      { id: 301, title: "SAP BW Consultant" },
      { id: 302, title: "SAP BI Developer" },
      { id: 303, title: "SAP Business Objects Analyst" },
      { id: 304, title: "SAP BW/BI Project Manager" },
      { id: 305, title: "SAP BW/BI Data Architect" },
      { id: 306, title: "SAP BW/BI Reporting Specialist" },
    ],
  },
  {
    id: 4,
    name: "SAP CRM",
    category: "Customer Relationship Management",
    designation: [
      { id: 401, title: "SAP CRM Functional Consultant" },
      { id: 402, title: "SAP CRM Technical Consultant" },
      { id: 403, title: "SAP CRM Business Analyst" },
      { id: 404, title: "SAP CRM Project Manager" },
      { id: 405, title: "SAP Hybris Developer" },
      { id: 406, title: "SAP CRM Marketing Specialist" },
    ],
  },
  {
    id: 5,
    name: "SAP HCM",
    category: "Human Capital Management",
    designation: [
      { id: 501, title: "SAP HCM Consultant" },
      { id: 502, title: "SAP HCM Payroll Specialist" },
      { id: 503, title: "SAP HCM SuccessFactors Analyst" },
      { id: 504, title: "SAP HCM Talent Management Consultant" },
      { id: 505, title: "SAP HCM Training Coordinator" },
      { id: 506, title: "SAP HCM Employee Relations Specialist" },
    ],
  },
  {
    id: 6,
    name: "SAP Ariba",
    category: "Procurement",
    designation: [
      { id: 601, title: "SAP Ariba Consultant" },
      { id: 602, title: "SAP Ariba Implementation Specialist" },
      { id: 603, title: "SAP Ariba Supplier Relationship Manager" },
      { id: 604, title: "SAP Ariba Procurement Analyst" },
      { id: 605, title: "SAP Ariba Sourcing Expert" },
      { id: 606, title: "SAP Ariba Contracts Administrator" },
    ],
  },
  {
    id: 7,
    name: "SAP SuccessFactors",
    category: "Human Capital Management",
    designation: [
      { id: 701, title: "SAP SuccessFactors Consultant" },
      { id: 702, title: "SAP SuccessFactors Employee Central Specialist" },
      { id: 703, title: "SAP SuccessFactors Performance and Goals Analyst" },
      { id: 704, title: "SAP SuccessFactors Learning Management Consultant" },
      { id: 705, title: "SAP SuccessFactors Recruiting Specialist" },
      { id: 706, title: "SAP SuccessFactors Compensation Analyst" },
    ],
  },
  {
    id: 8,
    name: "SAP Supply Chain Management",
    category: "Supply Chain",
    designation: [
      { id: 801, title: "SAP SCM Consultant" },
      { id: 802, title: "SAP Supply Chain Planner" },
      { id: 803, title: "SAP Warehouse Management Specialist" },
      { id: 804, title: "SAP Logistics Coordinator" },
      { id: 805, title: "SAP Demand Planning Analyst" },
      { id: 806, title: "SAP Procurement Specialist" },
    ],
  },
  {
    id: 9,
    name: "SAP Business Warehouse",
    category: "Business Intelligence",
    designation: [
      { id: 901, title: "SAP BW/BI Consultant" },
      { id: 902, title: "SAP BW/BI Data Modeler" },
      { id: 903, title: "SAP BW/BI Report Developer" },
      { id: 904, title: "SAP BW/BI Project Manager" },
      { id: 905, title: "SAP BW/BI Dashboard Specialist" },
      { id: 906, title: "SAP BW/BI Data Integration Expert" },
    ],
  },
  {
    id: 10,
    name: "SAP Leonardo",
    category: "Emerging Technologies",
    designation: [
      { id: 1001, title: "SAP Leonardo IoT Specialist" },
      { id: 1002, title: "SAP Leonardo Machine Learning Engineer" },
      { id: 1003, title: "SAP Leonardo Blockchain Analyst" },
      { id: 1004, title: "SAP Leonardo Analytics Consultant" },
      { id: 1005, title: "SAP Leonardo Cloud Platform Developer" },
      { id: 1006, title: "SAP Leonardo UX/UI Designer" },
    ],
  },
];
